ospf = {'vrf': {'default': {'address_family': {'ipv4': {'instance': {'1': {'adjacency_stagger': {'initial_number': 300,
                                                                                          'maximum_number': 300},
                                                                    'areas': {'0.0.0.0': {'area_id': '0.0.0.0',
                                                                                          'area_type': 'normal',
                                                                                          'database': {'lsa_types': {1: {'lsa_type': 1,
                                                                                                                         'lsas': {'192.168.0.1 192.168.0.1': {'adv_router': '192.168.0.1',
                                                                                                                                                              'lsa_id': '192.168.0.1',
                                                                                                                                                              'ospfv2': {'body': {'router': {'links': {'10.0.0.14': {'link_data': '10.0.0.13',
                                                                                                                                                                                                                     'link_id': '10.0.0.14',
                                                                                                                                                                                                                     'topologies': {0: {'metric': 1,
                                                                                                                                                                                                                                        'mt_id': 0}},
                                                                                                                                                                                                                     'type': 'transit '
                                                                                                                                                                                                                             'network'},
                                                                                                                                                                                                       '10.0.0.18': {'link_data': '10.0.0.17',
                                                                                                                                                                                                                     'link_id': '10.0.0.18',
                                                                                                                                                                                                                     'topologies': {0: {'metric': 1,
                                                                                                                                                                                                                                        'mt_id': 0}},
                                                                                                                                                                                                                     'type': 'transit '
                                                                                                                                                                                                                             'network'},
                                                                                                                                                                                                       '10.0.0.6': {'link_data': '10.0.0.5',
                                                                                                                                                                                                                    'link_id': '10.0.0.6',
                                                                                                                                                                                                                    'topologies': {0: {'metric': 1,
                                                                                                                                                                                                                                       'mt_id': 0}},
                                                                                                                                                                                                                    'type': 'transit '
                                                                                                                                                                                                                            'network'},
                                                                                                                                                                                                       '10.0.0.9': {'link_data': '10.0.0.9',
                                                                                                                                                                                                                    'link_id': '10.0.0.9',
                                                                                                                                                                                                                    'topologies': {0: {'metric': 1,
                                                                                                                                                                                                                                       'mt_id': 0}},
                                                                                                                                                                                                                    'type': 'transit '
                                                                                                                                                                                                                            'network'}},
                                                                                                                                                                                             'num_of_links': 4}},
                                                                                                                                                                         'header': {'adv_router': '192.168.0.1',
                                                                                                                                                                                    'age': 50,
                                                                                                                                                                                    'checksum': '0x1766',
                                                                                                                                                                                    'length': 72,
                                                                                                                                                                                    'lsa_id': '192.168.0.1',
                                                                                                                                                                                    'option': 'None',
                                                                                                                                                                                    'seq_num': '80000006',
                                                                                                                                                                                    'type': 1}}},
                                                                                                                                  '192.168.0.2 192.168.0.2': {'adv_router': '192.168.0.2',
                                                                                                                                                              'lsa_id': '192.168.0.2',
                                                                                                                                                              'ospfv2': {'body': {'router': {'links': {'10.0.0.21': {'link_data': '10.0.0.21',
                                                                                                                                                                                                                     'link_id': '10.0.0.21',
                                                                                                                                                                                                                     'topologies': {0: {'metric': 1,
                                                                                                                                                                                                                                        'mt_id': 0}},
                                                                                                                                                                                                                     'type': 'transit '
                                                                                                                                                                                                                             'network'},
                                                                                                                                                                                                       '10.0.0.26': {'link_data': '10.0.0.25',
                                                                                                                                                                                                                     'link_id': '10.0.0.26',
                                                                                                                                                                                                                     'topologies': {0: {'metric': 1,
                                                                                                                                                                                                                                        'mt_id': 0}},
                                                                                                                                                                                                                     'type': 'transit '
                                                                                                                                                                                                                             'network'},
                                                                                                                                                                                                       '10.0.0.30': {'link_data': '10.0.0.29',
                                                                                                                                                                                                                     'link_id': '10.0.0.30',
                                                                                                                                                                                                                     'topologies': {0: {'metric': 1,
                                                                                                                                                                                                                                        'mt_id': 0}},
                                                                                                                                                                                                                     'type': 'transit '
                                                                                                                                                                                                                             'network'},
                                                                                                                                                                                                       '10.0.0.6': {'link_data': '10.0.0.6',
                                                                                                                                                                                                                    'link_id': '10.0.0.6',
                                                                                                                                                                                                                    'topologies': {0: {'metric': 1,
                                                                                                                                                                                                                                       'mt_id': 0}},
                                                                                                                                                                                                                    'type': 'transit '
                                                                                                                                                                                                                            'network'}},
                                                                                                                                                                                             'num_of_links': 4}},
                                                                                                                                                                         'header': {'adv_router': '192.168.0.2',
                                                                                                                                                                                    'age': 70,
                                                                                                                                                                                    'checksum': '0xFB34',
                                                                                                                                                                                    'length': 72,
                                                                                                                                                                                    'lsa_id': '192.168.0.2',
                                                                                                                                                                                    'option': 'None',
                                                                                                                                                                                    'seq_num': '80000008',
                                                                                                                                                                                    'type': 1}}},
                                                                                                                                  '192.168.0.3 192.168.0.3': {'adv_router': '192.168.0.3',
                                                                                                                                                              'lsa_id': '192.168.0.3',
                                                                                                                                                              'ospfv2': {'body': {'router': {'links': {'10.0.0.21': {'link_data': '10.0.0.22',
                                                                                                                                                                                                                     'link_id': '10.0.0.21',
                                                                                                                                                                                                                     'topologies': {0: {'metric': 1,
                                                                                                                                                                                                                                        'mt_id': 0}},
                                                                                                                                                                                                                     'type': 'transit '
                                                                                                                                                                                                                             'network'},
                                                                                                                                                                                                       '10.0.0.34': {'link_data': '10.0.0.33',
                                                                                                                                                                                                                     'link_id': '10.0.0.34',
                                                                                                                                                                                                                     'topologies': {0: {'metric': 1,
                                                                                                                                                                                                                                        'mt_id': 0}},
                                                                                                                                                                                                                     'type': 'transit '
                                                                                                                                                                                                                             'network'},
                                                                                                                                                                                                       '10.0.0.38': {'link_data': '10.0.0.37',
                                                                                                                                                                                                                     'link_id': '10.0.0.38',
                                                                                                                                                                                                                     'topologies': {0: {'metric': 1,
                                                                                                                                                                                                                                        'mt_id': 0}},
                                                                                                                                                                                                                     'type': 'transit '
                                                                                                                                                                                                                             'network'},
                                                                                                                                                                                                       '10.0.0.9': {'link_data': '10.0.0.10',
                                                                                                                                                                                                                    'link_id': '10.0.0.9',
                                                                                                                                                                                                                    'topologies': {0: {'metric': 1,
                                                                                                                                                                                                                                       'mt_id': 0}},
                                                                                                                                                                                                                    'type': 'transit '
                                                                                                                                                                                                                            'network'}},
                                                                                                                                                                                             'num_of_links': 4}},
                                                                                                                                                                         'header': {'adv_router': '192.168.0.3',
                                                                                                                                                                                    'age': 40,
                                                                                                                                                                                    'checksum': '0xAF5A',
                                                                                                                                                                                    'length': 72,
                                                                                                                                                                                    'lsa_id': '192.168.0.3',
                                                                                                                                                                                    'option': 'None',
                                                                                                                                                                                    'seq_num': '80000004',
                                                                                                                                                                                    'type': 1}}},
                                                                                                                                  '192.168.0.4 192.168.0.4': {'adv_router': '192.168.0.4',
                                                                                                                                                              'lsa_id': '192.168.0.4',
                                                                                                                                                              'ospfv2': {'body': {'router': {'links': {'10.0.0.14': {'link_data': '10.0.0.14',
                                                                                                                                                                                                                     'link_id': '10.0.0.14',
                                                                                                                                                                                                                     'topologies': {0: {'metric': 1,
                                                                                                                                                                                                                                        'mt_id': 0}},
                                                                                                                                                                                                                     'type': 'transit '
                                                                                                                                                                                                                             'network'},
                                                                                                                                                                                                       '10.0.0.26': {'link_data': '10.0.0.26',
                                                                                                                                                                                                                     'link_id': '10.0.0.26',
                                                                                                                                                                                                                     'topologies': {0: {'metric': 1,
                                                                                                                                                                                                                                        'mt_id': 0}},
                                                                                                                                                                                                                     'type': 'transit '
                                                                                                                                                                                                                             'network'},
                                                                                                                                                                                                       '10.0.0.34': {'link_data': '10.0.0.34',
                                                                                                                                                                                                                     'link_id': '10.0.0.34',
                                                                                                                                                                                                                     'topologies': {0: {'metric': 1,
                                                                                                                                                                                                                                        'mt_id': 0}},
                                                                                                                                                                                                                     'type': 'transit '
                                                                                                                                                                                                                             'network'},
                                                                                                                                                                                                       '10.0.0.42': {'link_data': '10.0.0.41',
                                                                                                                                                                                                                     'link_id': '10.0.0.42',
                                                                                                                                                                                                                     'topologies': {0: {'metric': 1,
                                                                                                                                                                                                                                        'mt_id': 0}},
                                                                                                                                                                                                                     'type': 'transit '
                                                                                                                                                                                                                             'network'}},
                                                                                                                                                                                             'num_of_links': 4}},
                                                                                                                                                                         'header': {'adv_router': '192.168.0.4',
                                                                                                                                                                                    'age': 46,
                                                                                                                                                                                    'checksum': '0x3E4',
                                                                                                                                                                                    'length': 72,
                                                                                                                                                                                    'lsa_id': '192.168.0.4',
                                                                                                                                                                                    'option': 'None',
                                                                                                                                                                                    'seq_num': '80000009',
                                                                                                                                                                                    'type': 1}}},
                                                                                                                                  '192.168.0.5 192.168.0.5': {'adv_router': '192.168.0.5',
                                                                                                                                                              'lsa_id': '192.168.0.5',
                                                                                                                                                              'ospfv2': {'body': {'router': {'links': {'10.0.0.18': {'link_data': '10.0.0.18',
                                                                                                                                                                                                                     'link_id': '10.0.0.18',
                                                                                                                                                                                                                     'topologies': {0: {'metric': 1,
                                                                                                                                                                                                                                        'mt_id': 0}},
                                                                                                                                                                                                                     'type': 'transit '
                                                                                                                                                                                                                             'network'},
                                                                                                                                                                                                       '10.0.0.30': {'link_data': '10.0.0.30',
                                                                                                                                                                                                                     'link_id': '10.0.0.30',
                                                                                                                                                                                                                     'topologies': {0: {'metric': 1,
                                                                                                                                                                                                                                        'mt_id': 0}},
                                                                                                                                                                                                                     'type': 'transit '
                                                                                                                                                                                                                             'network'},
                                                                                                                                                                                                       '10.0.0.38': {'link_data': '10.0.0.38',
                                                                                                                                                                                                                     'link_id': '10.0.0.38',
                                                                                                                                                                                                                     'topologies': {0: {'metric': 1,
                                                                                                                                                                                                                                        'mt_id': 0}},
                                                                                                                                                                                                                     'type': 'transit '
                                                                                                                                                                                                                             'network'},
                                                                                                                                                                                                       '10.0.0.42': {'link_data': '10.0.0.42',
                                                                                                                                                                                                                     'link_id': '10.0.0.42',
                                                                                                                                                                                                                     'topologies': {0: {'metric': 1,
                                                                                                                                                                                                                                        'mt_id': 0}},
                                                                                                                                                                                                                     'type': 'transit '
                                                                                                                                                                                                                             'network'}},
                                                                                                                                                                                             'num_of_links': 4}},
                                                                                                                                                                         'header': {'adv_router': '192.168.0.5',
                                                                                                                                                                                    'age': 100,
                                                                                                                                                                                    'checksum': '0x6468',
                                                                                                                                                                                    'length': 72,
                                                                                                                                                                                    'lsa_id': '192.168.0.5',
                                                                                                                                                                                    'option': 'None',
                                                                                                                                                                                    'seq_num': '80000009',
                                                                                                                                                                                    'type': 1}}}}},
                                                                                                                     2: {'lsa_type': 2,
                                                                                                                         'lsas': {'10.0.0.14 192.168.0.4': {'adv_router': '192.168.0.4',
                                                                                                                                                            'lsa_id': '10.0.0.14',
                                                                                                                                                            'ospfv2': {'body': {'network': {'attached_routers': {'192.168.0.1': {},
                                                                                                                                                                                                                 '192.168.0.4': {}},
                                                                                                                                                                                            'network_mask': '255.255.255.252'}},
                                                                                                                                                                       'header': {'adv_router': '192.168.0.4',
                                                                                                                                                                                  'age': 827,
                                                                                                                                                                                  'checksum': '0x4995',
                                                                                                                                                                                  'length': 32,
                                                                                                                                                                                  'lsa_id': '10.0.0.14',
                                                                                                                                                                                  'option': 'None',
                                                                                                                                                                                  'seq_num': '80000002',
                                                                                                                                                                                  'type': 2}}},
                                                                                                                                  '10.0.0.18 192.168.0.5': {'adv_router': '192.168.0.5',
                                                                                                                                                            'lsa_id': '10.0.0.18',
                                                                                                                                                            'ospfv2': {'body': {'network': {'attached_routers': {'192.168.0.1': {},
                                                                                                                                                                                                                 '192.168.0.5': {}},
                                                                                                                                                                                            'network_mask': '255.255.255.252'}},
                                                                                                                                                                       'header': {'adv_router': '192.168.0.5',
                                                                                                                                                                                  'age': 865,
                                                                                                                                                                                  'checksum': '0x25B3',
                                                                                                                                                                                  'length': 32,
                                                                                                                                                                                  'lsa_id': '10.0.0.18',
                                                                                                                                                                                  'option': 'None',
                                                                                                                                                                                  'seq_num': '80000002',
                                                                                                                                                                                  'type': 2}}},
                                                                                                                                  '10.0.0.21 192.168.0.2': {'adv_router': '192.168.0.2',
                                                                                                                                                            'lsa_id': '10.0.0.21',
                                                                                                                                                            'ospfv2': {'body': {'network': {'attached_routers': {'192.168.0.2': {},
                                                                                                                                                                                                                 '192.168.0.3': {}},
                                                                                                                                                                                            'network_mask': '255.255.255.252'}},
                                                                                                                                                                       'header': {'adv_router': '192.168.0.2',
                                                                                                                                                                                  'age': 78,
                                                                                                                                                                                  'checksum': '0x17C2',
                                                                                                                                                                                  'length': 32,
                                                                                                                                                                                  'lsa_id': '10.0.0.21',
                                                                                                                                                                                  'option': 'None',
                                                                                                                                                                                  'seq_num': '80000002',
                                                                                                                                                                                  'type': 2}}},
                                                                                                                                  '10.0.0.26 192.168.0.4': {'adv_router': '192.168.0.4',
                                                                                                                                                            'lsa_id': '10.0.0.26',
                                                                                                                                                            'ospfv2': {'body': {'network': {'attached_routers': {'192.168.0.2': {},
                                                                                                                                                                                                                 '192.168.0.4': {}},
                                                                                                                                                                                            'network_mask': '255.255.255.252'}},
                                                                                                                                                                       'header': {'adv_router': '192.168.0.4',
                                                                                                                                                                                  'age': 827,
                                                                                                                                                                                  'checksum': '0xDEF2',
                                                                                                                                                                                  'length': 32,
                                                                                                                                                                                  'lsa_id': '10.0.0.26',
                                                                                                                                                                                  'option': 'None',
                                                                                                                                                                                  'seq_num': '80000002',
                                                                                                                                                                                  'type': 2}}},
                                                                                                                                  '10.0.0.30 192.168.0.5': {'adv_router': '192.168.0.5',
                                                                                                                                                            'lsa_id': '10.0.0.30',
                                                                                                                                                            'ospfv2': {'body': {'network': {'attached_routers': {'192.168.0.2': {},
                                                                                                                                                                                                                 '192.168.0.5': {}},
                                                                                                                                                                                            'network_mask': '255.255.255.252'}},
                                                                                                                                                                       'header': {'adv_router': '192.168.0.5',
                                                                                                                                                                                  'age': 865,
                                                                                                                                                                                  'checksum': '0xBA11',
                                                                                                                                                                                  'length': 32,
                                                                                                                                                                                  'lsa_id': '10.0.0.30',
                                                                                                                                                                                  'option': 'None',
                                                                                                                                                                                  'seq_num': '80000002',
                                                                                                                                                                                  'type': 2}}},
                                                                                                                                  '10.0.0.34 192.168.0.4': {'adv_router': '192.168.0.4',
                                                                                                                                                            'lsa_id': '10.0.0.34',
                                                                                                                                                            'ospfv2': {'body': {'network': {'attached_routers': {'192.168.0.3': {},
                                                                                                                                                                                                                 '192.168.0.4': {}},
                                                                                                                                                                                            'network_mask': '255.255.255.252'}},
                                                                                                                                                                       'header': {'adv_router': '192.168.0.4',
                                                                                                                                                                                  'age': 53,
                                                                                                                                                                                  'checksum': '0x9C2C',
                                                                                                                                                                                  'length': 32,
                                                                                                                                                                                  'lsa_id': '10.0.0.34',
                                                                                                                                                                                  'option': 'None',
                                                                                                                                                                                  'seq_num': '80000002',
                                                                                                                                                                                  'type': 2}}},
                                                                                                                                  '10.0.0.38 192.168.0.5': {'adv_router': '192.168.0.5',
                                                                                                                                                            'lsa_id': '10.0.0.38',
                                                                                                                                                            'ospfv2': {'body': {'network': {'attached_routers': {'192.168.0.3': {},
                                                                                                                                                                                                                 '192.168.0.5': {}},
                                                                                                                                                                                            'network_mask': '255.255.255.252'}},
                                                                                                                                                                       'header': {'adv_router': '192.168.0.5',
                                                                                                                                                                                  'age': 107,
                                                                                                                                                                                  'checksum': '0x784A',
                                                                                                                                                                                  'length': 32,
                                                                                                                                                                                  'lsa_id': '10.0.0.38',
                                                                                                                                                                                  'option': 'None',
                                                                                                                                                                                  'seq_num': '80000002',
                                                                                                                                                                                  'type': 2}}},
                                                                                                                                  '10.0.0.42 192.168.0.5': {'adv_router': '192.168.0.5',
                                                                                                                                                            'lsa_id': '10.0.0.42',
                                                                                                                                                            'ospfv2': {'body': {'network': {'attached_routers': {'192.168.0.4': {},
                                                                                                                                                                                                                 '192.168.0.5': {}},
                                                                                                                                                                                            'network_mask': '255.255.255.252'}},
                                                                                                                                                                       'header': {'adv_router': '192.168.0.5',
                                                                                                                                                                                  'age': 865,
                                                                                                                                                                                  'checksum': '0x5E5F',
                                                                                                                                                                                  'length': 32,
                                                                                                                                                                                  'lsa_id': '10.0.0.42',
                                                                                                                                                                                  'option': 'None',
                                                                                                                                                                                  'seq_num': '80000002',
                                                                                                                                                                                  'type': 2}}},
                                                                                                                                  '10.0.0.6 192.168.0.2': {'adv_router': '192.168.0.2',
                                                                                                                                                           'lsa_id': '10.0.0.6',
                                                                                                                                                           'ospfv2': {'body': {'network': {'attached_routers': {'192.168.0.1': {},
                                                                                                                                                                                                                '192.168.0.2': {}},
                                                                                                                                                                                           'network_mask': '255.255.255.252'}},
                                                                                                                                                                      'header': {'adv_router': '192.168.0.2',
                                                                                                                                                                                 'age': 827,
                                                                                                                                                                                 'checksum': '0x9159',
                                                                                                                                                                                 'length': 32,
                                                                                                                                                                                 'lsa_id': '10.0.0.6',
                                                                                                                                                                                 'option': 'None',
                                                                                                                                                                                 'seq_num': '80000002',
                                                                                                                                                                                 'type': 2}}},
                                                                                                                                  '10.0.0.9 192.168.0.1': {'adv_router': '192.168.0.1',
                                                                                                                                                           'lsa_id': '10.0.0.9',
                                                                                                                                                           'ospfv2': {'body': {'network': {'attached_routers': {'192.168.0.1': {},
                                                                                                                                                                                                                '192.168.0.3': {}},
                                                                                                                                                                                           'network_mask': '255.255.255.252'}},
                                                                                                                                                                      'header': {'adv_router': '192.168.0.1',
                                                                                                                                                                                 'age': 58,
                                                                                                                                                                                 'checksum': '0x8B5C',
                                                                                                                                                                                 'length': 32,
                                                                                                                                                                                 'lsa_id': '10.0.0.9',
                                                                                                                                                                                 'option': 'None',
                                                                                                                                                                                 'seq_num': '80000002',
                                                                                                                                                                                 'type': 2}}}}}}},
                                                                                          'interfaces': {'GigabitEthernet0/1': {'bdr_ip_addr': '10.0.0.5',
                                                                                                                                'bdr_router_id': '192.168.0.1',
                                                                                                                                'bfd': {'enable': False},
                                                                                                                                'cost': 1,
                                                                                                                                'dead_interval': 40,
                                                                                                                                'demand_circuit': False,
                                                                                                                                'dr_ip_addr': '10.0.0.6',
                                                                                                                                'dr_router_id': '192.168.0.2',
                                                                                                                                'enable': True,
                                                                                                                                'hello_interval': 10,
                                                                                                                                'hello_timer': '00:00:03',
                                                                                                                                'interface_type': 'broadcast',
                                                                                                                                'lls': True,
                                                                                                                                'name': 'GigabitEthernet0/1',
                                                                                                                                'neighbors': {'192.168.0.2': {'address': '10.0.0.6',
                                                                                                                                                              'bdr_ip_addr': '10.0.0.5',
                                                                                                                                                              'dead_timer': '00:00:37',
                                                                                                                                                              'dr_ip_addr': '10.0.0.6',
                                                                                                                                                              'neighbor_router_id': '192.168.0.2',
                                                                                                                                                              'state': 'full',
                                                                                                                                                              'statistics': {'nbr_event_count': 6,
                                                                                                                                                                             'nbr_retrans_qlen': 0}}},
                                                                                                                                'passive': False,
                                                                                                                                'priority': 1,
                                                                                                                                'retransmit_interval': 5,
                                                                                                                                'state': 'bdr',
                                                                                                                                'transmit_delay': 1},
                                                                                                         'GigabitEthernet0/2': {'bdr_ip_addr': '10.0.0.10',
                                                                                                                                'bdr_router_id': '192.168.0.3',
                                                                                                                                'bfd': {'enable': False},
                                                                                                                                'cost': 1,
                                                                                                                                'dead_interval': 40,
                                                                                                                                'demand_circuit': False,
                                                                                                                                'dr_ip_addr': '10.0.0.9',
                                                                                                                                'dr_router_id': '192.168.0.1',
                                                                                                                                'enable': True,
                                                                                                                                'hello_interval': 10,
                                                                                                                                'hello_timer': '00:00:01',
                                                                                                                                'interface_type': 'broadcast',
                                                                                                                                'lls': True,
                                                                                                                                'name': 'GigabitEthernet0/2',
                                                                                                                                'neighbors': {'192.168.0.3': {'address': '10.0.0.10',
                                                                                                                                                              'bdr_ip_addr': '10.0.0.10',
                                                                                                                                                              'dead_timer': '00:00:34',
                                                                                                                                                              'dr_ip_addr': '10.0.0.9',
                                                                                                                                                              'neighbor_router_id': '192.168.0.3',
                                                                                                                                                              'state': 'full',
                                                                                                                                                              'statistics': {'nbr_event_count': 6,
                                                                                                                                                                             'nbr_retrans_qlen': 0}}},
                                                                                                                                'passive': False,
                                                                                                                                'priority': 1,
                                                                                                                                'retransmit_interval': 5,
                                                                                                                                'state': 'dr',
                                                                                                                                'transmit_delay': 1},
                                                                                                         'GigabitEthernet0/3': {'bdr_ip_addr': '10.0.0.13',
                                                                                                                                'bdr_router_id': '192.168.0.1',
                                                                                                                                'bfd': {'enable': False},
                                                                                                                                'cost': 1,
                                                                                                                                'dead_interval': 40,
                                                                                                                                'demand_circuit': False,
                                                                                                                                'dr_ip_addr': '10.0.0.14',
                                                                                                                                'dr_router_id': '192.168.0.4',
                                                                                                                                'enable': True,
                                                                                                                                'hello_interval': 10,
                                                                                                                                'hello_timer': '00:00:01',
                                                                                                                                'interface_type': 'broadcast',
                                                                                                                                'lls': True,
                                                                                                                                'name': 'GigabitEthernet0/3',
                                                                                                                                'neighbors': {'192.168.0.4': {'address': '10.0.0.14',
                                                                                                                                                              'bdr_ip_addr': '10.0.0.13',
                                                                                                                                                              'dead_timer': '00:00:32',
                                                                                                                                                              'dr_ip_addr': '10.0.0.14',
                                                                                                                                                              'neighbor_router_id': '192.168.0.4',
                                                                                                                                                              'state': 'full',
                                                                                                                                                              'statistics': {'nbr_event_count': 6,
                                                                                                                                                                             'nbr_retrans_qlen': 0}}},
                                                                                                                                'passive': False,
                                                                                                                                'priority': 1,
                                                                                                                                'retransmit_interval': 5,
                                                                                                                                'state': 'bdr',
                                                                                                                                'transmit_delay': 1},
                                                                                                         'GigabitEthernet0/4': {'bdr_ip_addr': '10.0.0.17',
                                                                                                                                'bdr_router_id': '192.168.0.1',
                                                                                                                                'bfd': {'enable': False},
                                                                                                                                'cost': 1,
                                                                                                                                'dead_interval': 40,
                                                                                                                                'demand_circuit': False,
                                                                                                                                'dr_ip_addr': '10.0.0.18',
                                                                                                                                'dr_router_id': '192.168.0.5',
                                                                                                                                'enable': True,
                                                                                                                                'hello_interval': 10,
                                                                                                                                'hello_timer': '00:00:01',
                                                                                                                                'interface_type': 'broadcast',
                                                                                                                                'lls': True,
                                                                                                                                'name': 'GigabitEthernet0/4',
                                                                                                                                'neighbors': {'192.168.0.5': {'address': '10.0.0.18',
                                                                                                                                                              'bdr_ip_addr': '10.0.0.17',
                                                                                                                                                              'dead_timer': '00:00:38',
                                                                                                                                                              'dr_ip_addr': '10.0.0.18',
                                                                                                                                                              'neighbor_router_id': '192.168.0.5',
                                                                                                                                                              'state': 'full',
                                                                                                                                                              'statistics': {'nbr_event_count': 6,
                                                                                                                                                                             'nbr_retrans_qlen': 0}}},
                                                                                                                                'passive': False,
                                                                                                                                'priority': 1,
                                                                                                                                'retransmit_interval': 5,
                                                                                                                                'state': 'bdr',
                                                                                                                                'transmit_delay': 1}},
                                                                                          'mpls': {'te': {'enable': False}},
                                                                                          'statistics': {'area_scope_lsa_cksum_sum': '0x06D9D7',
                                                                                                         'area_scope_lsa_count': 15,
                                                                                                         'spf_runs_count': 7}}},
                                                                    'auto_cost': {'enable': False},
                                                                    'bfd': {'enable': False},
                                                                    'graceful_restart': {'cisco': {'enable': False,
                                                                                                   'type': 'cisco'},
                                                                                         'ietf': {'enable': False,
                                                                                                  'type': 'ietf'}},
                                                                    'mpls': {'ldp': {'autoconfig': True,
                                                                                     'autoconfig_area_id': '0.0.0.0',
                                                                                     'igp_sync': False}},
                                                                    'nsr': {'enable': False},
                                                                    'preference': {'single_value': {'all': 110}},
                                                                    'router_id': '192.168.0.1',
                                                                    'spf_control': {'paths': 4,
                                                                                    'throttle': {'spf': {'hold': 10000,
                                                                                                         'maximum': 10000,
                                                                                                         'start': 5000}}},
                                                                    'stub_router': {'always': {'always': False,
                                                                                               'external_lsa': False,
                                                                                               'include_stub': False,
                                                                                               'summary_lsa': False}}}}}}}}}
